# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsDaemon < Formula
  desc "Agent Receipts daemon and companion verify CLI"
  homepage "https://github.com/agent-receipts/ar/tree/main/daemon"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.8.0/daemon_0.8.0_darwin_amd64.tar.gz"
      sha256 "a7731889ac5b44743fa3aed68b6f88d35bffb995f58331ba5f62f946a9035797"

      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.8.0/daemon_0.8.0_darwin_arm64.tar.gz"
      sha256 "85c3575d16f370135cd269b764fd5c63def4e631b398211d9d88d8d86e142219"

      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.8.0/daemon_0.8.0_linux_amd64.tar.gz"
      sha256 "7d8909f8869accc9386ba73278d11c7af788ae24b40a2f7ed5149b2ca0f71468"
      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.8.0/daemon_0.8.0_linux_arm64.tar.gz"
      sha256 "46bc3fa82a644c4f3a4b1f720f1ecca3a7e815862770263ecb747ea4f2530702"
      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
  end

  service do
    run opt_bin/"agent-receipts-daemon"
    keep_alive true
    log_path var/"log/agent-receipts-daemon.log"
    error_log_path var/"log/agent-receipts-daemon.log"
    working_dir var
  end

  caveats <<~EOS
    Before starting the service for the first time, generate your signing key:
      agent-receipts-daemon --init

    Then start the daemon:
      brew services start agent-receipts/tap/agent-receipts-daemon

    Receipts database: ~/.local/share/agent-receipts/receipts.db
    Signing key:       ~/.local/share/agent-receipts/signing.key
    Socket:            $TMPDIR/agentreceipts/events.sock
  EOS

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^daemon\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/agent-receipts-daemon", "--version"
    system "#{bin}/agent-receipts", "--help"
  end
end
