# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsDaemonAlpha < Formula
  desc "Agent Receipts daemon and companion verify CLI (alpha/beta track)"
  homepage "https://github.com/agent-receipts/ar/tree/main/daemon"
  version "0.20.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.20.0-alpha.1/daemon_0.20.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "620303a778b7c6d5426b92dddd8d0fe8ce7a3aecba06d2059ee4f91e87d8987f"

      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.20.0-alpha.1/daemon_0.20.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "9b836fd6bb698d7f96c1cd6c42924c6531249f28633c368ab9a2450330cabc69"

      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.20.0-alpha.1/daemon_0.20.0-alpha.1_linux_amd64.tar.gz"
      sha256 "61ee1c03d1f628f5968635189104a024cb9dddd16c909d32c9c5c2178a91e869"
      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.20.0-alpha.1/daemon_0.20.0-alpha.1_linux_arm64.tar.gz"
      sha256 "094b6e24cc92a05df82f7469a5f60a709139c9f657aab373b246b2d033a57ae2"
      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
  end

  conflicts_with "agent-receipts-daemon", because: "both install the same binaries"

  def post_install
    (var/"log/agent-receipts").mkpath
  end

  service do
    run opt_bin/"agent-receipts-daemon"
    keep_alive crashed: true
    log_path var/"log/agent-receipts/daemon.log"
    error_log_path var/"log/agent-receipts/daemon.log"
  end

  def caveats
    <<~EOS
      This is the alpha/beta track — it tracks every release including pre-releases.
      For stable-only installs use: brew install agent-receipts/tap/agent-receipts-daemon

      Before starting the service for the first time, generate your signing key:
        agent-receipts-daemon --init

      Then start the daemon:
        brew services start agent-receipts/tap/agent-receipts-daemon-alpha

      Receipts database: $XDG_DATA_HOME/agent-receipts/receipts.db
                         (falls back to ~/.local/share/agent-receipts/receipts.db when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_DB
      Signing key:       $XDG_DATA_HOME/agent-receipts/signing.key
                         (falls back to ~/.local/share/agent-receipts/signing.key when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_KEY
      Socket (macOS):    $XDG_DATA_HOME/agent-receipts/events.sock
                         (falls back to ~/.local/share/agent-receipts/events.sock when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_SOCKET
      Socket (Linux):    $XDG_RUNTIME_DIR/agentreceipts/events.sock
                         (falls back to /run/agentreceipts/events.sock when $XDG_RUNTIME_DIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Daemon logs:       #{var}/log/agent-receipts/daemon.log
                         (stdout + stderr, written by launchd when started via `brew services`)
    EOS
  end

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^daemon\/v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/agent-receipts-daemon", "--version"
    system "#{bin}/agent-receipts", "--help"
  end
end
