# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsDaemon < Formula
  desc "Agent Receipts daemon and companion verify CLI"
  homepage "https://github.com/agent-receipts/ar/tree/main/daemon"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.10.0/daemon_0.10.0_darwin_amd64.tar.gz"
      sha256 "6c554c610c3474ba6cd0e5ed7eae30d9dea69875d7a6dcf09b7ec6d082929504"

      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.10.0/daemon_0.10.0_darwin_arm64.tar.gz"
      sha256 "fe65146ac61b555c2825cc5734e13f13907723f4b0880892772b399edef3ffdb"

      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.10.0/daemon_0.10.0_linux_amd64.tar.gz"
      sha256 "af23eaa360893b3b8534e1e777916fac22c8226af7a7d297630e748c5c6afdb4"
      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.10.0/daemon_0.10.0_linux_arm64.tar.gz"
      sha256 "b08350770b245b1bba13175d17ac8f3ba5016d3d0ad236c747b9d4e076dbdb19"
      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
  end

  def post_install
    (var/"log/agent-receipts").mkpath
  end

  service do
    run opt_bin/"agent-receipts-daemon"
    keep_alive crashed: true
    log_path var/"log/agent-receipts/daemon.log"
    error_log_path var/"log/agent-receipts/daemon.log"
  end

  def caveats
    <<~EOS
      agent-receipts-hook is now a separate formula. If you previously installed
      it via this formula, run:
        brew install agent-receipts/tap/agent-receipts-hook

      Before starting the service for the first time, generate your signing key:
        agent-receipts-daemon --init

      Then start the daemon:
        brew services start agent-receipts/tap/agent-receipts-daemon

      Receipts database: $XDG_DATA_HOME/agent-receipts/receipts.db
                         (falls back to ~/.local/share/agent-receipts/receipts.db when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_DB
      Signing key:       $XDG_DATA_HOME/agent-receipts/signing.key
                         (falls back to ~/.local/share/agent-receipts/signing.key when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_KEY
      Socket (macOS):    $TMPDIR/agentreceipts/events.sock
                         (falls back to /tmp/agentreceipts/events.sock when $TMPDIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Socket (Linux):    $XDG_RUNTIME_DIR/agentreceipts/events.sock
                         (falls back to /run/agentreceipts/events.sock when $XDG_RUNTIME_DIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Daemon logs:       #{var}/log/agent-receipts/daemon.log
                         (stdout + stderr, written by launchd when started via `brew services`)
    EOS
  end

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^daemon\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/agent-receipts-daemon", "--version"
    system "#{bin}/agent-receipts", "--help"
  end
end
