# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsHook < Formula
  desc "Claude Code PostToolUse hook that forwards tool-call events to agent-receipts-daemon"
  homepage "https://github.com/agent-receipts/ar/tree/main/hook"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.9.0/agent-receipts-hook_0.9.0_darwin_amd64.tar.gz"
      sha256 "f5e4ec20ca62f79134cac4d8f987ec63b5bc1c911eda187142f966853bbb779d"

      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.9.0/agent-receipts-hook_0.9.0_darwin_arm64.tar.gz"
      sha256 "3190b2641a5281a650a45ca71c9a5331954e39cd4586cfa802b861f809a0c426"

      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.9.0/agent-receipts-hook_0.9.0_linux_amd64.tar.gz"
      sha256 "ee70514814f02c5ab3c88343f58f3713c49f7f22a13897eb052e1923fd6eecfa"
      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.9.0/agent-receipts-hook_0.9.0_linux_arm64.tar.gz"
      sha256 "1b5dcb71703fb53238ae7bddfd630fbe7d3d88d1ec0c595167f3ecf316ccf4f6"
      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
  end

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^hook\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/agent-receipts-hook"
  end
end
