# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsHookAlpha < Formula
  desc "Hook that forwards agent tool-call events to the agent-receipts daemon (alpha/beta track)"
  homepage "https://github.com/agent-receipts/ar/tree/main/hook"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.18.0/agent-receipts-hook_0.18.0_darwin_amd64.tar.gz"
      sha256 "4e4d51f57da068bb9732faf2842021e07d250d1ec43c779bb12c589fc4eb166f"

      define_method(:install) do
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.18.0/agent-receipts-hook_0.18.0_darwin_arm64.tar.gz"
      sha256 "c276c20ff7743cd9d59bea26ada302219c19f7cb7e2ef86442cfa1066a2cdbf5"

      define_method(:install) do
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.18.0/agent-receipts-hook_0.18.0_linux_amd64.tar.gz"
      sha256 "5befb2ffa45f295e721466ae8b76232ff0600843981dd5a7878186133929b8d5"
      define_method(:install) do
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.18.0/agent-receipts-hook_0.18.0_linux_arm64.tar.gz"
      sha256 "da23127a6f4ea6950209cac633b416b5c663567b87ab258d6f6837042881230a"
      define_method(:install) do
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
  end

  conflicts_with "agent-receipts-hook", because: "both install the same binaries"

  def caveats
    <<~EOS
      This is the alpha/beta track — it tracks every release including pre-releases.
      For stable-only installs use: brew install agent-receipts/tap/agent-receipts-hook

      The hook binary is now obsigna-hook (was agent-receipts-hook). The
      agent-receipts-hook command still works as a thin deprecation shim that
      forwards to obsigna-hook, so existing runtime hook configs keep running
      — but update them to obsigna-hook when convenient; the shim will be
      removed in a future release.
    EOS
  end

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^hook\/v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/obsigna-hook", "--version"
    system "#{bin}/agent-receipts-hook", "--version"
  end
end
