# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsHookAlpha < Formula
  desc "Claude Code PostToolUse hook that forwards tool-call events to agent-receipts-daemon (alpha/beta track)"
  homepage "https://github.com/agent-receipts/ar/tree/main/hook"
  version "0.14.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.14.0-alpha.1/agent-receipts-hook_0.14.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "d13fefdd4c5ecd34cb83df4fd4f3f393ea3362854bef576177ca7c74c3cdb152"

      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.14.0-alpha.1/agent-receipts-hook_0.14.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "49cef9f7040a6e0a2967e42c9c8e8f1a90135f447be4cf252630968e612e6b8f"

      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.14.0-alpha.1/agent-receipts-hook_0.14.0-alpha.1_linux_amd64.tar.gz"
      sha256 "99fe23b82e617dc02626e0dbf7a4bd0c21acac9f9e3a6576e9e9789dbe56a6fc"
      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.14.0-alpha.1/agent-receipts-hook_0.14.0-alpha.1_linux_arm64.tar.gz"
      sha256 "c8adb87af22d8927441ac5b2a63f4a392f052616305139de0236d3ece526eec8"
      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
  end

  conflicts_with "agent-receipts-hook", because: "both install the same binary"

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^hook\/v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/agent-receipts-hook", "--version"
  end
end
