# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsDaemonAlpha < Formula
  desc "Agent Receipts daemon and companion verify CLI (alpha/beta track)"
  homepage "https://github.com/agent-receipts/obsigna/tree/main/daemon"
  version "0.22.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/obsigna/releases/download/daemon%2Fv0.22.0-alpha.1/daemon_0.22.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "8e7b2c9bad994ab2770f46974b208e2f45abe700e350c4cb1df81e217f6b7c81"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/obsigna/releases/download/daemon%2Fv0.22.0-alpha.1/daemon_0.22.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "8a8a8a09f064e86551283c7bae47977b407cc34ba0994169afcb02682ea54557"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/daemon%2Fv0.22.0-alpha.1/daemon_0.22.0-alpha.1_linux_amd64.tar.gz"
      sha256 "3312cd18bbc84c67abce49e6d8cbc4fc467a569a7711fd7f7b2de27d841506f2"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/daemon%2Fv0.22.0-alpha.1/daemon_0.22.0-alpha.1_linux_arm64.tar.gz"
      sha256 "800c5f42d017ccb501f29af85ed8229118892fcf95cb61b361993f1c075144d5"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
  end

  conflicts_with "agent-receipts-daemon", because: "both install the same binaries"

  def post_install
    (var/"log/agent-receipts").mkpath
  end

  service do
    run opt_bin/"obsigna-daemon"
    keep_alive crashed: true
    log_path var/"log/agent-receipts/daemon.log"
    error_log_path var/"log/agent-receipts/daemon.log"
  end

  def caveats
    <<~EOS
      This is the alpha/beta track — it tracks every release including pre-releases.
      For stable-only installs use: brew install agent-receipts/tap/agent-receipts-daemon

      The daemon binary is now obsigna-daemon (was agent-receipts-daemon).
      If you reference the old binary name in any install script, systemd unit,
      launchd plist, or `brew services` wrapper, update it to obsigna-daemon and
      restart the service after upgrading:
        brew services restart agent-receipts/tap/agent-receipts-daemon-alpha

      Before starting the service for the first time, generate your signing key:
        obsigna-daemon --init

      Then start the daemon:
        brew services start agent-receipts/tap/agent-receipts-daemon-alpha

      Receipts database: $XDG_DATA_HOME/agent-receipts/receipts.db
                         (falls back to ~/.local/share/agent-receipts/receipts.db when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_DB
      Signing key:       $XDG_DATA_HOME/agent-receipts/signing.key
                         (falls back to ~/.local/share/agent-receipts/signing.key when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_KEY
      Socket (macOS):    $XDG_DATA_HOME/agent-receipts/events.sock
                         (falls back to ~/.local/share/agent-receipts/events.sock when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_SOCKET
      Socket (Linux):    $XDG_RUNTIME_DIR/agentreceipts/events.sock
                         (falls back to /run/agentreceipts/events.sock when $XDG_RUNTIME_DIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Daemon logs:       #{var}/log/agent-receipts/daemon.log
                         (stdout + stderr, written by launchd when started via `brew services`)
    EOS
  end

  livecheck do
    url "https://github.com/agent-receipts/obsigna"
    strategy :github_releases
    regex(/^daemon\/v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/obsigna-daemon", "--version"
    system "#{bin}/obsigna", "--help"
    system "#{bin}/agent-receipts", "--help"
  end
end
