# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsDaemon < Formula
  desc "Agent Receipts daemon and companion verify CLI"
  homepage "https://github.com/agent-receipts/ar/tree/main/daemon"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.9.0/daemon_0.9.0_darwin_amd64.tar.gz"
      sha256 "48458114126d6e192c79e8c464cdf4ed05beecbb14e1065558103e8a46c87b63"

      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.9.0/daemon_0.9.0_darwin_arm64.tar.gz"
      sha256 "4a7c09667f0ae1c94bd55ff073f1f569ee1012c58b06c0ec51889d883beb61a1"

      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.9.0/daemon_0.9.0_linux_amd64.tar.gz"
      sha256 "05e3c2a13131268622325fc36d8dea569fef78118d765f6cf6b5c6bfcfd8535e"
      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/daemon%2Fv0.9.0/daemon_0.9.0_linux_arm64.tar.gz"
      sha256 "5f076e91b36c648938ff26b629a7ddb4f2da401e5450575cbf7aa4390e6824dc"
      define_method(:install) do
        bin.install "agent-receipts-daemon"
        bin.install "agent-receipts"
      end
    end
  end

  def post_install
    (var/"log/agent-receipts").mkpath
  end

  service do
    run opt_bin/"agent-receipts-daemon"
    keep_alive crashed: true
    log_path var/"log/agent-receipts/daemon.log"
    error_log_path var/"log/agent-receipts/daemon.log"
  end

  def caveats
    <<~EOS
      agent-receipts-hook is now a separate formula. If you previously installed
      it via this formula, run:
        brew install agent-receipts/tap/agent-receipts-hook

      Before starting the service for the first time, generate your signing key:
        agent-receipts-daemon --init

      Then start the daemon:
        brew services start agent-receipts/tap/agent-receipts-daemon

      Receipts database: $XDG_DATA_HOME/agent-receipts/receipts.db
                         (falls back to ~/.local/share/agent-receipts/receipts.db when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_DB
      Signing key:       $XDG_DATA_HOME/agent-receipts/signing.key
                         (falls back to ~/.local/share/agent-receipts/signing.key when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_KEY
      Socket (macOS):    $TMPDIR/agentreceipts/events.sock
                         (falls back to /tmp/agentreceipts/events.sock when $TMPDIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Socket (Linux):    $XDG_RUNTIME_DIR/agentreceipts/events.sock
                         (falls back to /run/agentreceipts/events.sock when $XDG_RUNTIME_DIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Daemon logs:       #{var}/log/agent-receipts/daemon.log
                         (stdout + stderr, written by launchd when started via `brew services`)
    EOS
  end

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^daemon\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/agent-receipts-daemon", "--version"
    system "#{bin}/agent-receipts", "--help"
  end
end
