# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentReceiptsHookAlpha < Formula
  desc "Claude Code PostToolUse hook that forwards tool-call events to agent-receipts-daemon (alpha/beta track)"
  homepage "https://github.com/agent-receipts/ar/tree/main/hook"
  version "0.17.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.17.0-alpha.1/agent-receipts-hook_0.17.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "01002f31003160288fade1c5c3a6dd2f5897ca565509a3c70678460039d3080b"

      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.17.0-alpha.1/agent-receipts-hook_0.17.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "913d8674a160ed173c3498a834438849911ccc17aedaf0eddcd83c049118312b"

      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.17.0-alpha.1/agent-receipts-hook_0.17.0-alpha.1_linux_amd64.tar.gz"
      sha256 "4c4097a252cb2c4ec56a399fe7a88ad2193abbca0ee078e4aa7e1c97e8717e3c"
      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/hook%2Fv0.17.0-alpha.1/agent-receipts-hook_0.17.0-alpha.1_linux_arm64.tar.gz"
      sha256 "120b18d15c2d0f11d874a8377e386a6d1085b5683ae4e414961d95345342f6ba"
      define_method(:install) do
        bin.install "agent-receipts-hook"
      end
    end
  end

  conflicts_with "agent-receipts-hook", because: "both install the same binary"

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^hook\/v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/agent-receipts-hook", "--version"
  end
end
