# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Collector < Formula
  desc "Agent Receipts reference HTTP collector — append-only signed-receipt sink"
  homepage "https://github.com/agent-receipts/ar/tree/main/collector"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/collector%2Fv0.13.0/collector_0.13.0_darwin_amd64.tar.gz"
      sha256 "1330a9f94e3da667ff6ea680c44edfde17c19b10a7cbf577ec91180cc0d6ac8e"

      define_method(:install) do
        bin.install "collector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/collector%2Fv0.13.0/collector_0.13.0_darwin_arm64.tar.gz"
      sha256 "eb5f91cdd0633add928264500a7ac4f808a29cd0500a5534b3ef20228a64d066"

      define_method(:install) do
        bin.install "collector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/collector%2Fv0.13.0/collector_0.13.0_linux_amd64.tar.gz"
      sha256 "6ec745fe875c19de0405bc833c809b29e06ea57130a0a2315ad4717d71fdf916"
      define_method(:install) do
        bin.install "collector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/collector%2Fv0.13.0/collector_0.13.0_linux_arm64.tar.gz"
      sha256 "becd1b93ffb8ee43b778517a6f35ae1e77ca56bc93ce67f7cfd280a82ce88c34"
      define_method(:install) do
        bin.install "collector"
      end
    end
  end

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^collector\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/collector", "--version"
  end
end
