# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dashboard < Formula
  desc "Local web UI for browsing Agent Receipts SQLite databases"
  homepage "https://github.com/agent-receipts/dashboard"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.7.0/dashboard_0.7.0_darwin_amd64.tar.gz"
      sha256 "ace428093551ab4eae8e967697ea4aa13826207a29183f58ee40bd1f66d4ee96"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.7.0/dashboard_0.7.0_darwin_arm64.tar.gz"
      sha256 "58227a97f4f7380e72b47de6a8f735029adbb9f8ff62f345b170c56cef309f4c"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.7.0/dashboard_0.7.0_linux_amd64.tar.gz"
      sha256 "f57146afabd5197e2ebf785ea54e0d4e6dfb63e533d4d1a3e5b55bf030f543cc"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.7.0/dashboard_0.7.0_linux_arm64.tar.gz"
      sha256 "24b2d166819796d9005e5e172d7d158b8cdab224dc9de5381d6543cdcd890c24"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  livecheck do
    url "https://github.com/agent-receipts/dashboard"
    strategy :github_releases
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/dashboard", "--version"
  end
end
