# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dashboard < Formula
  desc "Local web UI for browsing Agent Receipts SQLite databases"
  homepage "https://github.com/agent-receipts/dashboard"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.1.3/dashboard_0.1.3_darwin_amd64.tar.gz"
      sha256 "571c85683fc4a7459b086850d593b79a54ad619fca361ebe15f9782018bb79e7"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.1.3/dashboard_0.1.3_darwin_arm64.tar.gz"
      sha256 "8e6a6d3f1a203e14ad0d21ef5aa0b9b68509bae9e6eecb96609ea1a79c1ec0f0"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.1.3/dashboard_0.1.3_linux_amd64.tar.gz"
      sha256 "9bbf0379b4239e82dbcf9ffca8ea9dd3aa46c3ae5dbc0c02ac1b13d3a1e8e6a9"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.1.3/dashboard_0.1.3_linux_arm64.tar.gz"
      sha256 "ee1a5e7419f10fd1bcb7d9645df83d81e13aa81a25a2b54fac17903ca290a639"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  livecheck do
    url "https://github.com/agent-receipts/dashboard"
    strategy :github_releases
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/dashboard", "--version"
  end
end
