# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DashboardAlpha < Formula
  desc "Local web UI for browsing Agent Receipts SQLite databases (alpha/beta track)"
  homepage "https://github.com/agent-receipts/dashboard"
  version "0.7.0-alpha.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.7.0-alpha.3/dashboard_0.7.0-alpha.3_darwin_amd64.tar.gz"
      sha256 "457912b58d6993743a87bdbac398b6c028d9ea1f2fc808e113e0c44a3e6766a6"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.7.0-alpha.3/dashboard_0.7.0-alpha.3_darwin_arm64.tar.gz"
      sha256 "dc3c725f1a184057d9d84ec5bbbce41e95c91d6369ee39e9d27f3e644ce13e7b"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.7.0-alpha.3/dashboard_0.7.0-alpha.3_linux_amd64.tar.gz"
      sha256 "18448d1d59cfcb92f56deff8160fd261f62fb34fb794fb581700a3e6543d0845"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.7.0-alpha.3/dashboard_0.7.0-alpha.3_linux_arm64.tar.gz"
      sha256 "882df122897a30d7f31bfad83d89f6d23c1f9f63770b040cd2031589655e7e4a"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  conflicts_with "dashboard", because: "both install the same binary"

  livecheck do
    url "https://github.com/agent-receipts/dashboard"
    strategy :github_releases
    regex(/^v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/dashboard", "--version"
  end
end
