# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dashboard < Formula
  desc "Local web UI for browsing Agent Receipts SQLite databases"
  homepage "https://github.com/agent-receipts/dashboard"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.14.0/dashboard_0.14.0_darwin_amd64.tar.gz"
      sha256 "62c37839585ece0d72904602e6064534555f93071cf7fbdf858feb99ca499661"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.14.0/dashboard_0.14.0_darwin_arm64.tar.gz"
      sha256 "1888f6d4da49098f28cf9a0b77ed3435ce61aca6ddc0e40756e45938a7a60418"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.14.0/dashboard_0.14.0_linux_amd64.tar.gz"
      sha256 "73f4ac6378007c60352eb00188860d28fca01072bc97eeb90bf19c78b4ec954b"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.14.0/dashboard_0.14.0_linux_arm64.tar.gz"
      sha256 "07c051cf310b16856d9b13c18bb9bd6b2258957a53081e78723b87f76cd65d98"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  livecheck do
    url "https://github.com/agent-receipts/dashboard"
    strategy :github_releases
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/dashboard", "--version"
  end
end
