# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DashboardAlpha < Formula
  desc "Local web UI for browsing Agent Receipts SQLite databases (alpha/beta track)"
  homepage "https://github.com/agent-receipts/dashboard"
  version "0.9.0-alpha.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.9.0-alpha.3/dashboard_0.9.0-alpha.3_darwin_amd64.tar.gz"
      sha256 "d1147543688c6f3c92d1f00e92173b2bd96105e43086ff854d2fd2f3fb064693"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.9.0-alpha.3/dashboard_0.9.0-alpha.3_darwin_arm64.tar.gz"
      sha256 "3ee5d1f91c2b6d568b4eef5096433ab016c8fa9eaede1e18f07b4094539c47e5"

      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.9.0-alpha.3/dashboard_0.9.0-alpha.3_linux_amd64.tar.gz"
      sha256 "64a9feaa07640c09cb36f131b896ff261a185129b749efbfa9a130dd9f4b8712"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/dashboard/releases/download/v0.9.0-alpha.3/dashboard_0.9.0-alpha.3_linux_arm64.tar.gz"
      sha256 "505699930c0e12a4c345f27dbc1e756d62cd44742531d840b44a206bde1d3011"
      define_method(:install) do
        bin.install "dashboard"
      end
    end
  end

  conflicts_with "dashboard", because: "both install the same binary"

  livecheck do
    url "https://github.com/agent-receipts/dashboard"
    strategy :github_releases
    regex(/^v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/dashboard", "--version"
  end
end
