# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpProxy < Formula
  desc "MCP proxy with action receipts, policy engine, and intent tracking"
  homepage "https://github.com/agent-receipts/ar/tree/main/mcp-proxy"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.6.1/mcp-proxy_0.6.1_darwin_amd64.tar.gz"
      sha256 "3d1ce3819102e6eee037f6d36297d58a01508b914781b4f140ec1cff9169f7a0"

      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.6.1/mcp-proxy_0.6.1_darwin_arm64.tar.gz"
      sha256 "0ad12d51f92bc11790a5f3bb2f0aac7dbb4c6a8cdac2360f1e87d6536dab6b83"

      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.6.1/mcp-proxy_0.6.1_linux_amd64.tar.gz"
      sha256 "12bde619fc71fa341074d772b76e03068ed5ba2ce6e39da1c1d29850f350cf7d"
      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.6.1/mcp-proxy_0.6.1_linux_arm64.tar.gz"
      sha256 "9fa5380dca137654cd481ce7e453402e30bc7db370483552f5d5759cb6ec7191"
      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
  end

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^mcp-proxy\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/mcp-proxy", "--version"
  end
end
