# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpProxy < Formula
  desc "MCP proxy with action receipts, policy engine, and intent tracking"
  homepage "https://github.com/agent-receipts/ar/tree/main/mcp-proxy"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.6.2/mcp-proxy_0.6.2_darwin_amd64.tar.gz"
      sha256 "0fab9024249cdfa68f27ff75d4138c592415a5502331fef872253eccaf588f08"

      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.6.2/mcp-proxy_0.6.2_darwin_arm64.tar.gz"
      sha256 "364431cf836bbcf35cdf94865472efea18a0e358aeff1172a508233e62bf16c9"

      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.6.2/mcp-proxy_0.6.2_linux_amd64.tar.gz"
      sha256 "9375d0a7b438759d2a21dd3845e9ec05c53f5dabfc7acacccc9986825b5b0c2b"
      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.6.2/mcp-proxy_0.6.2_linux_arm64.tar.gz"
      sha256 "2fedafbeeae7c2dae6857bd9abb80813e4773354f6edc8be699dbf7f2bbdc1a2"
      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
  end

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^mcp-proxy\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/mcp-proxy", "--version"
  end
end
