# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpProxyAlpha < Formula
  desc "MCP proxy with action receipts, policy engine, and intent tracking (alpha/beta track)"
  homepage "https://github.com/agent-receipts/ar/tree/main/mcp-proxy"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.14.0/mcp-proxy_0.14.0_darwin_amd64.tar.gz"
      sha256 "d16cb639d952ac0237ce3aefb41b337584a3a5be2120b86311eb0b0f4261c11d"

      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.14.0/mcp-proxy_0.14.0_darwin_arm64.tar.gz"
      sha256 "3d6871fa79993c416a31796dde573120a6fafb42b938deb6eff4cb5d6bf52123"

      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.14.0/mcp-proxy_0.14.0_linux_amd64.tar.gz"
      sha256 "31208a4a1be7fccf7cb3af1c160c1fe792e809853de7b93423836b7f474a0cf8"
      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.14.0/mcp-proxy_0.14.0_linux_arm64.tar.gz"
      sha256 "cab4c0715379983602fb73b144d4dbde505f63707f10521c5804e4fbdb04d6d1"
      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
  end

  conflicts_with "mcp-proxy", because: "both install the same binary"

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^mcp-proxy\/v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/mcp-proxy", "--version"
  end
end
