# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpProxyAlpha < Formula
  desc "MCP proxy with action receipts, policy engine, and intent tracking (alpha/beta track)"
  homepage "https://github.com/agent-receipts/ar/tree/main/mcp-proxy"
  version "0.14.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.14.0-alpha.1/mcp-proxy_0.14.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "a96af4f957fd8f4dea3bbe60c20de538b25b7ff565db896963b96fa155a5921a"

      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.14.0-alpha.1/mcp-proxy_0.14.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "abf290e2ac72833dae858e4101a550788b446515193d788bc32724d6c717d11c"

      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.14.0-alpha.1/mcp-proxy_0.14.0-alpha.1_linux_amd64.tar.gz"
      sha256 "748961fb3c5fb52820011304805e041b19e0999e6ea8435f203516404d0f1183"
      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/ar/releases/download/mcp-proxy%2Fv0.14.0-alpha.1/mcp-proxy_0.14.0-alpha.1_linux_arm64.tar.gz"
      sha256 "36422464f47cc5edae0e767a7406422a0438b8dffcdfc2aa2f3c87f22a4697b7"
      define_method(:install) do
        bin.install "mcp-proxy"
      end
    end
  end

  conflicts_with "mcp-proxy", because: "both install the same binary"

  livecheck do
    url "https://github.com/agent-receipts/ar"
    strategy :github_releases
    regex(/^mcp-proxy\/v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/mcp-proxy", "--version"
  end
end
