# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObsignaDaemon < Formula
  desc "Agent Receipts daemon and companion verify CLI"
  homepage "https://github.com/agent-receipts/obsigna/tree/main/daemon"
  version "0.23.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/obsigna/releases/download/daemon%2Fv0.23.0/daemon_0.23.0_darwin_amd64.tar.gz"
      sha256 "90265059960e56b67b0d4ec971f565fb4e386d4bc4d748b9654667f89bc69161"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/obsigna/releases/download/daemon%2Fv0.23.0/daemon_0.23.0_darwin_arm64.tar.gz"
      sha256 "b1a2b5b5c70fde200bd27be66bddf002f4b64f544ae2ed58e5bbd4abf477f563"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/daemon%2Fv0.23.0/daemon_0.23.0_linux_amd64.tar.gz"
      sha256 "6f2c4118daf5c495179647f3dbd73b088b09fac7d314a0410adb0fe39b89e1cb"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/daemon%2Fv0.23.0/daemon_0.23.0_linux_arm64.tar.gz"
      sha256 "a8ad485330ac9f82ec919b3b512f9cb348cbe66e709d5248bcf315dffa487a71"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
  end

  def post_install
    (var/"log/agent-receipts").mkpath
  end

  service do
    run opt_bin/"obsigna-daemon"
    keep_alive crashed: true
    log_path var/"log/agent-receipts/daemon.log"
    error_log_path var/"log/agent-receipts/daemon.log"
  end

  def caveats
    <<~EOS
      The daemon binary is now obsigna-daemon (was agent-receipts-daemon).
      If you reference the old binary name in any install script, systemd unit,
      launchd plist, or `brew services` wrapper, update it to obsigna-daemon and
      restart the service after upgrading:
        brew services restart agent-receipts/tap/obsigna-daemon

      agent-receipts-hook is now a separate formula. If you previously installed
      it via this formula, run:
        brew install agent-receipts/tap/agent-receipts-hook

      Before starting the service for the first time, generate your signing key:
        obsigna-daemon --init

      Then start the daemon:
        brew services start agent-receipts/tap/obsigna-daemon

      Receipts database: $XDG_DATA_HOME/agent-receipts/receipts.db
                         (falls back to ~/.local/share/agent-receipts/receipts.db when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_DB
      Signing key:       $XDG_DATA_HOME/agent-receipts/signing.key
                         (falls back to ~/.local/share/agent-receipts/signing.key when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_KEY
      Socket (macOS):    $XDG_DATA_HOME/agent-receipts/events.sock
                         (falls back to ~/.local/share/agent-receipts/events.sock when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_SOCKET
      Socket (Linux):    $XDG_RUNTIME_DIR/agentreceipts/events.sock
                         (falls back to /run/agentreceipts/events.sock when $XDG_RUNTIME_DIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Daemon logs:       #{var}/log/agent-receipts/daemon.log
                         (stdout + stderr, written by launchd when started via `brew services`)
    EOS
  end

  conflicts_with "obsigna-daemon-alpha", because: "both install the same binaries"

  livecheck do
    url "https://github.com/agent-receipts/obsigna"
    strategy :github_releases
    regex(/^daemon\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/obsigna-daemon", "--version"
    system "#{bin}/obsigna", "--help"
    system "#{bin}/agent-receipts", "--help"
  end
end
