# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obsigna < Formula
  desc "Obsigna — Agent Receipts CLI, signing daemon, and verify tooling"
  homepage "https://github.com/agent-receipts/obsigna/tree/main/daemon"
  version "0.28.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.28.0/obsigna_0.28.0_darwin_amd64.tar.gz"
      sha256 "81fed3c90b03c504fa851242eae322493a957f7510058cb600bc84987782be35"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
        bin.install "obsigna-mcp"
        bin.install "mcp-proxy"
        bin.install "obsigna-collector"
        bin.install "collector"
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.28.0/obsigna_0.28.0_darwin_arm64.tar.gz"
      sha256 "517838380fec6ababc1a68240e596d7e368eef34ce98199310e565ff8026990e"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
        bin.install "obsigna-mcp"
        bin.install "mcp-proxy"
        bin.install "obsigna-collector"
        bin.install "collector"
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.28.0/obsigna_0.28.0_linux_amd64.tar.gz"
      sha256 "4f88fc508057035922b6e6cd97df30a5a0f08ca77b3a3b60624654fa7c131ac1"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
        bin.install "obsigna-mcp"
        bin.install "mcp-proxy"
        bin.install "obsigna-collector"
        bin.install "collector"
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.28.0/obsigna_0.28.0_linux_arm64.tar.gz"
      sha256 "e03a5a5eee30a7357876a134b2d8929ad310ef19d695345f99bd7e0869f144b4"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
        bin.install "obsigna-mcp"
        bin.install "mcp-proxy"
        bin.install "obsigna-collector"
        bin.install "collector"
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
  end

  def post_install
    (var/"log/agent-receipts").mkpath
  end

  service do
    run opt_bin/"obsigna-daemon"
    keep_alive crashed: true
    log_path var/"log/agent-receipts/daemon.log"
    error_log_path var/"log/agent-receipts/daemon.log"
  end

  def caveats
    <<~EOS
      This formula now installs the whole Obsigna toolset (ADR-0034): the
      obsigna CLI, the obsigna-daemon signer, obsigna-mcp (the MCP proxy,
      run via `obsigna mcp run`), obsigna-collector (the receipt hub, run via
      `obsigna collector run`), and obsigna-hook (the per-tool-call emission
      callback). Each ships alongside its deprecation shim (agent-receipts,
      mcp-proxy, collector, agent-receipts-hook), which forwards to the new
      binary — update references when convenient; the shims will be removed
      in a future release. The retired mcp-proxy, collector, and
      agent-receipts-hook formulae are migrated to this one via the tap's
      tap_migrations.json, so `brew update && brew upgrade` moves you with no
      manual step.

      The daemon binary is now obsigna-daemon (was agent-receipts-daemon).
      If you reference the old binary name in any install script, systemd unit,
      launchd plist, or `brew services` wrapper, update it to obsigna-daemon and
      restart the service after upgrading:
        brew services restart agent-receipts/tap/obsigna

      Before starting the service for the first time, generate your signing key:
        obsigna-daemon --init

      Then start the daemon:
        brew services start agent-receipts/tap/obsigna

      Receipts database: $XDG_DATA_HOME/agent-receipts/receipts.db
                         (falls back to ~/.local/share/agent-receipts/receipts.db when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_DB
      Signing key:       $XDG_DATA_HOME/agent-receipts/signing.key
                         (falls back to ~/.local/share/agent-receipts/signing.key when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_KEY
      Socket (macOS):    $XDG_DATA_HOME/agent-receipts/events.sock
                         (falls back to ~/.local/share/agent-receipts/events.sock when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_SOCKET
      Socket (Linux):    $XDG_RUNTIME_DIR/agentreceipts/events.sock
                         (falls back to /run/agentreceipts/events.sock when $XDG_RUNTIME_DIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Daemon logs:       #{var}/log/agent-receipts/daemon.log
                         (stdout + stderr, written by launchd when started via `brew services`)
    EOS
  end

  conflicts_with "obsigna-alpha", because: "both install the same binaries"

  livecheck do
    url "https://github.com/agent-receipts/obsigna"
    strategy :github_releases
    regex(/^obsigna\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/obsigna-daemon", "--version"
    system "#{bin}/obsigna", "--help"
    system "#{bin}/agent-receipts", "--help"
    system "#{bin}/obsigna-mcp", "--version"
    system "#{bin}/mcp-proxy", "--version"
    system "#{bin}/obsigna-collector", "--version"
    system "#{bin}/collector", "--version"
    system "#{bin}/obsigna-hook", "--version"
    system "#{bin}/agent-receipts-hook", "--version"
  end
end
