# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obsigna < Formula
  desc "Obsigna — Agent Receipts CLI, signing daemon, and verify tooling"
  homepage "https://github.com/agent-receipts/obsigna/tree/main/daemon"
  version "0.24.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.24.0/obsigna_0.24.0_darwin_amd64.tar.gz"
      sha256 "8635745e4c77c6fc1b0e41d37c6058d27320a29e745a9660118bd41d08c946a6"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.24.0/obsigna_0.24.0_darwin_arm64.tar.gz"
      sha256 "0e70a8592b10b0ed3d9f39845252ced1c1bb5333b55e63d20ddb145c5af868a5"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.24.0/obsigna_0.24.0_linux_amd64.tar.gz"
      sha256 "e5bf0114d330e175c13fee7be3eb49b818eb705cdc5c73909a332799a70cbb97"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.24.0/obsigna_0.24.0_linux_arm64.tar.gz"
      sha256 "4811ddb239aabc3211968b16b6470dc728d3d70c440f7110272faeb9af7d26e7"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
      end
    end
  end

  def post_install
    (var/"log/agent-receipts").mkpath
  end

  service do
    run opt_bin/"obsigna-daemon"
    keep_alive crashed: true
    log_path var/"log/agent-receipts/daemon.log"
    error_log_path var/"log/agent-receipts/daemon.log"
  end

  def caveats
    <<~EOS
      The daemon binary is now obsigna-daemon (was agent-receipts-daemon).
      If you reference the old binary name in any install script, systemd unit,
      launchd plist, or `brew services` wrapper, update it to obsigna-daemon and
      restart the service after upgrading:
        brew services restart agent-receipts/tap/obsigna

      agent-receipts-hook is now a separate formula. If you previously installed
      it via this formula, run:
        brew install agent-receipts/tap/agent-receipts-hook

      Before starting the service for the first time, generate your signing key:
        obsigna-daemon --init

      Then start the daemon:
        brew services start agent-receipts/tap/obsigna

      Receipts database: $XDG_DATA_HOME/agent-receipts/receipts.db
                         (falls back to ~/.local/share/agent-receipts/receipts.db when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_DB
      Signing key:       $XDG_DATA_HOME/agent-receipts/signing.key
                         (falls back to ~/.local/share/agent-receipts/signing.key when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_KEY
      Socket (macOS):    $XDG_DATA_HOME/agent-receipts/events.sock
                         (falls back to ~/.local/share/agent-receipts/events.sock when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_SOCKET
      Socket (Linux):    $XDG_RUNTIME_DIR/agentreceipts/events.sock
                         (falls back to /run/agentreceipts/events.sock when $XDG_RUNTIME_DIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Daemon logs:       #{var}/log/agent-receipts/daemon.log
                         (stdout + stderr, written by launchd when started via `brew services`)
    EOS
  end

  conflicts_with "obsigna-alpha", because: "both install the same binaries"

  livecheck do
    url "https://github.com/agent-receipts/obsigna"
    strategy :github_releases
    regex(/^obsigna\/v?(\d+(?:\.\d+)+)$/i)
  end

  test do
    system "#{bin}/obsigna-daemon", "--version"
    system "#{bin}/obsigna", "--help"
    system "#{bin}/agent-receipts", "--help"
  end
end
