# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObsignaAlpha < Formula
  desc "Obsigna — Agent Receipts CLI, signing daemon, and verify tooling (alpha/beta track)"
  homepage "https://github.com/agent-receipts/obsigna/tree/main/daemon"
  version "0.25.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.25.0/obsigna_0.25.0_darwin_amd64.tar.gz"
      sha256 "c27e037a20d7b9af3944c70a34c912a1e580c84ba98e6faec54cbe5869b6f4a3"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
        bin.install "obsigna-mcp"
        bin.install "mcp-proxy"
        bin.install "obsigna-collector"
        bin.install "collector"
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.25.0/obsigna_0.25.0_darwin_arm64.tar.gz"
      sha256 "ab811ab87040664e3d2c0fde78f739148c3feceb3d9e9d88804eb6844694cf11"

      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
        bin.install "obsigna-mcp"
        bin.install "mcp-proxy"
        bin.install "obsigna-collector"
        bin.install "collector"
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.25.0/obsigna_0.25.0_linux_amd64.tar.gz"
      sha256 "eec4e92943825f12ff3922e3b5013db582cf1a015ac1533b2423f6ed5ae7e704"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
        bin.install "obsigna-mcp"
        bin.install "mcp-proxy"
        bin.install "obsigna-collector"
        bin.install "collector"
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-receipts/obsigna/releases/download/obsigna%2Fv0.25.0/obsigna_0.25.0_linux_arm64.tar.gz"
      sha256 "b0dae85d439a36ca79ee267e5afd49c4f99905bca897ed1fa637621b8fa5b0bd"
      define_method(:install) do
        bin.install "obsigna-daemon"
        bin.install "obsigna"
        bin.install "agent-receipts"
        bin.install "obsigna-mcp"
        bin.install "mcp-proxy"
        bin.install "obsigna-collector"
        bin.install "collector"
        bin.install "obsigna-hook"
        bin.install "agent-receipts-hook"
      end
    end
  end

  conflicts_with "obsigna", because: "both install the same binaries"

  def post_install
    (var/"log/agent-receipts").mkpath
  end

  service do
    run opt_bin/"obsigna-daemon"
    keep_alive crashed: true
    log_path var/"log/agent-receipts/daemon.log"
    error_log_path var/"log/agent-receipts/daemon.log"
  end

  def caveats
    <<~EOS
      This is the alpha/beta track — it tracks every release including pre-releases.
      For stable-only installs use: brew install agent-receipts/tap/obsigna

      This formula now installs the whole Obsigna toolset (ADR-0034): the
      obsigna CLI, the obsigna-daemon signer, obsigna-mcp (the MCP proxy,
      run via `obsigna mcp run`), obsigna-collector (the receipt hub, run via
      `obsigna collector run`), and obsigna-hook (the per-tool-call emission
      callback), each alongside its deprecation shim (agent-receipts,
      mcp-proxy, collector, agent-receipts-hook).

      The daemon binary is now obsigna-daemon (was agent-receipts-daemon).
      If you reference the old binary name in any install script, systemd unit,
      launchd plist, or `brew services` wrapper, update it to obsigna-daemon and
      restart the service after upgrading:
        brew services restart agent-receipts/tap/obsigna-alpha

      Before starting the service for the first time, generate your signing key:
        obsigna-daemon --init

      Then start the daemon:
        brew services start agent-receipts/tap/obsigna-alpha

      Receipts database: $XDG_DATA_HOME/agent-receipts/receipts.db
                         (falls back to ~/.local/share/agent-receipts/receipts.db when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_DB
      Signing key:       $XDG_DATA_HOME/agent-receipts/signing.key
                         (falls back to ~/.local/share/agent-receipts/signing.key when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_KEY
      Socket (macOS):    $XDG_DATA_HOME/agent-receipts/events.sock
                         (falls back to ~/.local/share/agent-receipts/events.sock when $XDG_DATA_HOME is unset or relative)
                         Override: AGENTRECEIPTS_SOCKET
      Socket (Linux):    $XDG_RUNTIME_DIR/agentreceipts/events.sock
                         (falls back to /run/agentreceipts/events.sock when $XDG_RUNTIME_DIR is unset)
                         Override: AGENTRECEIPTS_SOCKET
      Daemon logs:       #{var}/log/agent-receipts/daemon.log
                         (stdout + stderr, written by launchd when started via `brew services`)
    EOS
  end

  livecheck do
    url "https://github.com/agent-receipts/obsigna"
    strategy :github_releases
    regex(/^obsigna\/v?(\d+(?:\.\d+)+(?:-[a-z0-9.]+)?)$/i)
  end

  test do
    system "#{bin}/obsigna-daemon", "--version"
    system "#{bin}/obsigna", "--help"
    system "#{bin}/agent-receipts", "--help"
    system "#{bin}/obsigna-mcp", "--version"
    system "#{bin}/mcp-proxy", "--version"
    system "#{bin}/obsigna-collector", "--version"
    system "#{bin}/collector", "--version"
    system "#{bin}/obsigna-hook", "--version"
    system "#{bin}/agent-receipts-hook", "--version"
  end
end
